adapt tangoAttrZeroDController for Sardana v3.03
ALBA-Synchrotron/sardana-tango pull request #3
Opened 2020-09-14 08:54 UTC by dschick

2020-09-14 21:20 UTC, reszelaz commented
@rhomspuron could you please review this one? Thanks!

2020-09-29 16:17 UTC, rhomspuron requested changes
Hi @dschick, 

Thanks for the PR. 

The ReadTangoAttribute class is used on the TangoAttrCTCtrl. I propose you to create a module: tango_reader.py where you move the class ReadTangoAttributes and use the same for both controller, in this way we have a common.

2020-09-29 16:17 UTC, rhomspuron commented on sardana_tango/ctrl/TangoAttrZeroDCtrl.py
> +                            v = eval(formula)
You can change to:
value = float(dev_attr_value.value)
v = eval(formula, {'value': value, 'VALUE': value, 'Value':value}

2021-01-12 15:32 UTC, rhomspuron commented
Hi @dschick,

I will integrate the PR and add a TODO for the changes. I do not have permission to your branch, I will create another PR with your changes.

2021-01-12 15:34 UTC, closed without merging